apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: shepherd-build-app
spec:
  params:
    - name: image_tomcat
      type: string
    - name: container_tomcat
      type: string
    - name: tomcat_docker_version
      type: string
    - name: mysql_user
      type: string
    - name: mysql_pass
      type: string
    - name: container_mysql
      type: string
    - name: container_mongo
      type: string
    - name: tls_keystore_file
      type: string
    - name: tls_keystore_pass
      type: string
    - name: alias
      type: string
    - name: https_port
      type: string
  workspaces:
    - name: source
      description: SecurityShepherd build directory
      mountPath: /SecurityShepherd
  steps:
    - name: build-environment
      image: maven:3.6.3-openjdk-8
      script: |
        mvn -Pdocker clean install -DskipTests
      env:
        - name: "IMAGE_TOMCAT"
          value: "$(params.image_tomcat)"
        - name: "CONTAINER_TOMCAT"
          value: "$(params.container_tomcat)"
        - name: "TOMCAT_DOCKER_VERSION"
          value: "$(params.tomcat_docker_version)"
        - name: "MYSQL_USER"
          value: "$(params.mysql_user)"
        - name: "MYSQL_PASS"
          value: "$(params.mysql_pass)"
        - name: "CONTAINER_MYSQL"
          value: "$(params.container_mysql)"
        - name: "CONTAINER_MONGO"
          value: "$(params.container_mongo)"
        - name: "TLS_KEYSTORE_FILE"
          value: "$(params.tls_keystore_file)"
        - name: "TLS_KEYSTORE_PASS"
          value: "$(params.tls_keystore_pass)"
        - name: "ALIAS"
          value: "$(params.alias)"
        - name: "HTTPS_PORT"
          value: "$(params.https_port)"
